"""Add Deck model and relation with Card

Revision ID: f2a06fb10564
Revises: 525b696612e1
Create Date: 2024-12-18 14:36:15.735448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a06fb10564'
down_revision = '525b696612e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'deck', ['deck_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deck_id')

    op.drop_table('deck')
    # ### end Alembic commands ###
