"""Add DrawnCard tracking table

Revision ID: fa8257d68b59
Revises: f2a06fb10564
Create Date: 2024-12-30 12:05:54.496656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8257d68b59'
down_revision = 'f2a06fb10564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawn_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('is_drawn', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('ALGORITHMS', 'LANGUAGE', 'MATH', 'SYSTEM_DESIGN', name='deckcategory', native_enum=False),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('ALGORITHMS', 'LANGUAGE', 'MATH', 'SYSTEM_DESIGN', name='deckcategory', native_enum=False),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    op.drop_table('drawn_card')
    # ### end Alembic commands ###
